version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"                  # e.g., us-west-2
    AWS_ACCOUNT_ID: "905418229977"      # e.g., 123456789012
    REPO_NAME: "ameera-app"                # e.g., ECR Repo Name
    IMAGE_TAG: "latest" 
    ecs_container_name: "app"                       # You can change this if needed

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - echo Contents of imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
    files: imagedefinitions.json
